### ISSUE TITLE
Problem with get forms function

### ISSUE THREAD

**Issue by nickjetten** [GearPlug/typeform-python#1]
Hi,

I am trying to get some data from Typeform into Python using the API Wrapper.

```
import typeform
client = Client('mykeyhere')
myforms = client.get_forms()
```

But then it gives an error in the parse object:

  File "/Users/nick/anaconda3/lib/python3.6/site-packages/typeform/client.py", line 54, in _parse
    raise exception.Forbidden(message)

UnboundLocalError: local variable 'message' referenced before assignment

Any suggestions?

**Comment by gustav0** [comment]
This is indeed an error with our code. We applied a quick fix with this commit [8dc9aea](https://github.com/GearPlug/typeform-python/commit/8dc9aea1fd7f79444f1ad973f7c23d78bcde6abf).
With this you should be able to see the complete error response.

Anyways, your problem seems to be an access issue. Please double check your credentials.

Hope this helps.

**Comment by andrefaure** [comment]
Hi,

This function also gives an error for me (using Authorized Access):

`from typeform.client import Client
client = Client('TOKEN')
client.get_forms()`

Output:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ajfaure/.virtualenvs/django2/lib/python3.6/site-packages/typeform/client.py", line 147, in get_forms
    return self._get(endpoint='forms').json()
  File "/home/ajfaure/.virtualenvs/django2/lib/python3.6/site-packages/typeform/client.py", line 26, in _get
    return self._request('GET', endpoint, data=data, params=params)
  File "/home/ajfaure/.virtualenvs/django2/lib/python3.6/site-packages/typeform/client.py", line 39, in _request
    return self._parse(response)
  File "/home/ajfaure/.virtualenvs/django2/lib/python3.6/site-packages/typeform/client.py", line 61, in _parse
    raise exception.Forbidden(message)
typeform.exception.Forbidden: {'message': 'please provide a valid key', 'status': 403}

Any idea how to fix this?

Thanks,

Andre

**Comment by ingmferrer** [comment]
Hello,

I've updated this library to version 0.2.0, that means your issue is now fixed.

Please read the changes at https://github.com/GearPlug/typeform-python/releases/tag/v0.2.0

Remember to read the updated README.md

If you have any other issue/question, don't hesitate to open a new issue.
